import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import "../../assets/css/index.css"
import BackToTop from "@/components/BackToTop";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Spree Commerce",
    description: "Generated by create Spree Commerce",
    icons: {
        icon: "/LogoBlack.png", // đường dẫn tính từ /public
    },
};

const RootLayout = ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {

    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col w-full h-full`}
            >
                <BackToTop />
                <main className="min-h-[60vh]">{children}</main>
            </body>
        </html>
    );
}

export default RootLayout